# Tools4AI Configuration for Agent Misalignment
agent.provider=openai
openAiKey=
openAiBaseURL=https://integrate.api.nvidia.com/v1
openAiModelName=nvidia/llama-3.1-nemotron-70b-instruct
t4a.action.packages=io.github.vishalmysore.misalignment.examples
t4a.ai.model=openai
# Ensure we scan our package
action.packages.to.scan=io.github.vishalmysore.misalignment.examples
